# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 11:37
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_databank.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lizard_auth_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200, unique=True, verbose_name='unique identifier')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='identifier')),
                ('uuid', model_databank.db.fields.UUIDField(blank=True, editable=False, max_length=36)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_repo_update', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lizard_auth_client.Organisation')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ModelUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=200, verbose_name='unique identifier')),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FilePathField(max_length=255)),
                ('is_processed', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('model_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='model_databank.ModelReference')),
                ('model_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_databank.ModelType', verbose_name='model type')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lizard_auth_client.Organisation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='comment')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model_references', models.ManyToManyField(related_name='provider', to='model_databank.ModelReference')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='comment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='model_databank.ModelReference')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_databank.Version')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='model_databank.Version'),
        ),
        migrations.AddField(
            model_name='modelreference',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_databank.ModelType', verbose_name='model type'),
        ),
    ]
